<?php

use Autio\Models\Model;
use Autio\Models\Make;
use Illuminate\Database\Seeder;

class ModelsTableSeeder extends Seeder
{
  public function run()
  {
    // TODO: Abstract this big ol' array into a different file
    $models = [
      'Acura' => [
        'CL',
        'Integra',
        'Legend',
        'MDX',
        'NSX',
        'RDX',
        'RL',
        'RSX',
        'SLX',
        'TL',
        'TSX',
        'Vigor',
        'ZDX'
      ],

      'Aston Martin' => [
        'DB9 Volante',
        'DB9',
        'DBS',
        'Rapide',
        'V12 Vantage',
        'V8 Vantage S',
        'V8 Vantage',
        'Vanquish S',
        'Vantage',
        'Virage',
      ],

      'Audi' => [
        '100',
        '200',
        '4000',
        '4000CS Quattro',
        '4000s Quattro',
        '4000s',
        '5000CS Quattro',
        '5000CS',
        '5000S',
        '80',
        '80/90',
        '90',
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'Allroad',
        'Cabriolet',
        'Coupe GT',
        'Coupe Quattro',
        'Q5',
        'Q7',
        'Quattro',
        'R8',
        'riolet',
        'RS 4',
        'RS 6',
        'RS4',
        'RS6',
        'S4',
        'S5',
        'S6',
        'S8',
        'TT',
        'V8',
      ],

      'BMW' => [
        '1 Series',
        '3 Series',
        '325',
        '330',
        '5 Series',
        '525',
        '530',
        '545',
        '550',
        '6 Series',
        '600',
        '645',
        '650',
        '7 Series',
        '745',
        '750',
        '760',
        '8 Series',
        'Alpina B7',
        'M Roadster',
        'M',
        'M3',
        'M5',
        'M6',
        'X3',
        'X5 M',
        'X5',
        'X6 M',
        'X6',
        'Z3',
        'Z4 M Roadster',
        'Z4 M',
        'Z4',
        'Z8',
      ],

      'Buick' => [
        'Century',
        'Coachbuilder',
        'Electra',
        'Enclave',
        'Estate',
        'Hearse',
        'LaCrosse',
        'LeSabre',
        'Lucerne',
        'Park Avenue',
        'Rainier',
        'Reatta',
        'Regal',
        'Rendezvous',
        'Riviera',
        'Roadmaster',
        'Skyhawk',
        'Skylark',
        'Somerset',
        'Special',
        'Terraza',
        'Verano',
      ],

      'Cadillac' => [
        'Allante',
        'Brougham',
        'Catera',
        'CTS-V',
        'CTS',
        'DeVille',
        'DTS',
        'Eldorado',
        'Escalade ESV',
        'Escalade EXT',
        'Escalade',
        'Fleetwood',
        'Seville',
        'Sixty Special',
        'SRX',
        'STS-V',
        'STS',
        'XLR-V',
        'XLR',
      ],

      'Chevrolet' => [
        '1500',
        '2500',
        '3500',
        'APV',
        'Astro',
        'Avalanche 1500',
        'Avalanche 2500',
        'Avalanche',
        'Aveo',
        'Bel Air',
        'Beretta',
        'Blazer',
        'Camaro',
        'Caprice Classic',
        'Caprice',
        'Cavalier',
        'Citation',
        'Classic',
        'Cobalt SS',
        'Cobalt',
        'Colorado',
        'Corsica',
        'Corvair 500',
        'Corvair',
        'Corvette',
        'Cruze',
        'Equinox',
        'Express 1500',
        'Express 2500',
        'Express 3500',
        'Express',
        'G-Series 1500',
        'G-Series 2500',
        'G-Series 3500',
        'G-Series G10',
        'G-Series G20',
        'G-Series G30',
        'HHR Panel',
        'HHR',
        'Impala SS',
        'Impala',
        'K5 Blazer',
        'Lumina APV',
        'Lumina',
        'LUV',
        'Malibu Maxx',
        'Malibu',
        'Metro',
        'Monte Carlo',
        'Monza',
        'Prizm',
        'S10 Blazer',
        'S10',
        'Silverado 1500',
        'Silverado 2500',
        'Silverado 3500',
        'Silverado 3500HD',
        'Silverado Hybrid',
        'Silverado',
        'Sonic',
        'Sportvan G10',
        'Sportvan G20',
        'Sportvan G30',
        'SSR',
        'Suburban 1500',
        'Suburban 2500',
        'Suburban',
        'Tahoe',
        'Tracker',
        'Trailblazer',
        'Traverse',
        'Uplander',
        'Vega',
        'Venture',
        'Volt',
      ],

      'Chrysler' => [
        '200',
        '300',
        '300C',
        '300M',
        'Aspen',
        'Cirrus',
        'Concorde',
        'Crossfire Roadster',
        'Crossfire',
        'Fifth Ave',
        'Grand Voyager',
        'Imperial',
        'LeBaron',
        'LHS',
        'New Yorker',
        'Pacifica',
        'Prowler',
        'PT Cruiser',
        'Sebring',
        'Town & Country',
        'Voyager',
      ],

      'Dodge' => [
        'Aries',
        'Aspen',
        'Avenger',
        'Caliber',
        'Caravan',
        'Challenger',
        'Charger',
        'Colt',
        'D150 Club',
        'D150',
        'D250 Club',
        'D250',
        'D350 Club',
        'D350',
        'Dakota Club',
        'Dakota',
        'Daytona',
        'Durango',
        'Dynasty',
        'Grand Caravan',
        'Intrepid',
        'Journey',
        'Magnum',
        'Monaco',
        'Neon',
        'Nitro',
        'Omni',
        'Ram 1500 Club',
        'Ram 1500',
        'Ram 2500 Club',
        'Ram 2500',
        'Ram 3500 Club',
        'Ram 3500',
        'Ram 50',
        'Ram Van 1500',
        'Ram Van 2500',
        'Ram Van 3500',
        'Ram Van B150',
        'Ram Van B250',
        'Ram Van B350',
        'Ram Wagon B150',
        'Ram Wagon B250',
        'Ram Wagon B350',
        'Ram',
        'Ramcharger',
        'Shadow',
        'Spirit',
        'Sprinter',
        'Stealth',
        'Stratus',
        'Viper RT/10',
        'Viper',
      ],

      'Fiat' => [
        '500',
        'Nuova 500',
      ],

      'Ford' => [
        'Aerostar',
        'Aspire',
        'Bronco II',
        'Bronco',
        'C-MAX Hybrid',
        'Club Wagon',
        'Contour',
        'Country',
        'Courier',
        'Crown Victoria',
        'E-350 Super Duty Van',
        'E-350 Super Duty',
        'E-Series',
        'E150',
        'E250',
        'E350',
        'Econoline E150',
        'Econoline E250',
        'Econoline E350',
        'Edge',
        'Escape',
        'Escort ZX2',
        'Escort',
        'Excursion',
        'EXP',
        'Expedition EL',
        'Expedition',
        'Explorer Sport Trac',
        'Explorer Sport',
        'Explorer',
        'F-250 Super Duty',
        'F-350 Super Duty',
        'F-Series Super Duty',
        'F-Series',
        'F150',
        'F250',
        'F350',
        'F450',
        'Fairlane',
        'Falcon',
        'Festiva',
        'Fiesta',
        'Five Hundred',
        'Flex',
        'Focus ST',
        'Focus',
        'Freestar',
        'Freestyle',
        'Fusion',
        'Galaxie',
        'GT',
        'GT500',
        'Laser',
        'Lightning',
        'LTD Crown Victoria',
        'LTD',
        'Mustang',
        'Probe',
        'Ranger',
        'Taurus X',
        'Taurus',
        'Tempo',
        'Th!nk',
        'Thunderbird',
        'Torino',
        'Transit Connect',
        'Windstar',
        'ZX2',
      ],

      'Geo' => [
        'Metro',
        'Prizm',
        'Storm',
        'Tracker',
      ],

      'GMC' => [
        '1500 Club Coupe',
        '1500',
        '2500 Club Coupe',
        '2500',
        '3500 Club Coupe',
        '3500',
        'Acadia',
        'Canyon',
        'Envoy XL',
        'Envoy XUV',
        'Envoy',
        'EV1',
        'Jimmy',
        'Rally Wagon 1500',
        'Rally Wagon 2500',
        'Rally Wagon 3500',
        'Rally Wagon G2500',
        'Rally Wagon G3500',
        'Safari',
        'Savana 1500',
        'Savana 2500',
        'Savana 3500',
        'Savana Cargo Van',
        'Savana',
        'Sierra 1500',
        'Sierra 2500',
        'Sierra 2500HD',
        'Sierra 3500',
        'Sierra 3500HD',
        'Sierra Denali',
        'Sierra Hybrid',
        'Sierra',
        'Sonoma Club Coupe',
        'Sonoma Club',
        'Sonoma',
        'Suburban 1500',
        'Suburban 2500',
        'Terrain',
        'Vandura 1500',
        'Vandura 2500',
        'Vandura 3500',
        'Vandura G1500',
        'Vandura G2500',
        'Vandura G3500',
        'Yukon Denali',
        'Yukon XL 1500',
        'Yukon XL 2500',
        'Yukon XL',
        'Yukon',
      ],

      'Honda' => [
        'Accord Crosstour',
        'Accord',
        'Civic GX',
        'Civic Si',
        'Civic',
        'CR-V',
        'CR-X',
        'CR-Z',
        'Crosstour',
        'del Sol',
        'Element',
        'FCX Clarity',
        'Fit',
        'Insight',
        'Odyssey',
        'Passport',
        'Pilot',
        'Prelude',
        'Ridgeline',
        'S2000',
      ],

      'Hummer' => [
        'H1',
        'H2 SUT',
        'H2 SUV',
        'H2',
        'H3',
        'H3T',
      ],

      'Hyundai' => [
        'Accent',
        'Azera',
        'Elantra',
        'Entourage',
        'Equus',
        'Excel',
        'Genesis Coupe',
        'Genesis',
        'HED-5',
        'Santa Fe',
        'Scoupe',
        'Sonata',
        'Tiburon',
        'Tucson',
        'Veloster',
        'Veracruz',
        'XG300',
        'XG350',
      ],

      'Infiniti' => [
        'EX',
        'FX',
        'G',
        'G25',
        'G35',
        'G37',
        'I',
        'IPL G',
        'J',
        'JX',
        'M',
        'Q',
        'QX',
        'QX56',
      ],

      'Jaguar' => [
        'S-Type',
        'X-Type',
        'XF',
        'XJ Series',
        'XJ',
        'XK Series',
        'XK',
      ],

      'Jeep' => [
        'Cherokee',
        'Comanche',
        'Commander',
        'Compass',
        'Grand Cherokee',
        'Liberty',
        'Patriot',
        'Wrangler',
      ],

      'Kia' => [
        'Amanti',
        'Borrego',
        'Carens',
        'Forte',
        'Mentor',
        'Mohave/Borrego',
        'Optima',
        'Rio',
        'Rio5',
        'Rondo',
        'Sedona',
        'Sephia',
        'Sorento',
        'Soul',
        'Spectra',
        'Spectra5',
        'Sportage',
      ],

      'Lexus' => [
        'CT',
        'ES',
        'GS',
        'GX',
        'HS',
        'IS F',
        'IS-F',
        'IS',
        'LFA',
        'LS Hybrid',
        'LS',
        'LX',
        'RX Hybrid',
        'RX',
        'SC',
      ],

      'Lincoln' => [
        'Aviator',
        'Blackwood',
        'Continental Mark VII',
        'Continental',
        'LS',
        'Mark LT',
        'Mark VII',
        'Mark VIII',
        'MKS',
        'MKT',
        'MKX',
        'MKZ',
        'Navigator L',
        'Navigator',
        'Town Car',
        'Zephyr',
      ],

      'Mazda' => [
        '323',
        '626',
        '929',
        'B-Series Plus',
        'B-Series',
        'B2000',
        'B2500',
        'B2600',
        'CX-5',
        'CX-7',
        'CX-9',
        'Familia',
        'GLC',
        'Mazda2',
        'Mazda3',
        'Mazda5',
        'Mazda6 5-Door',
        'Mazda6 Sport',
        'Mazda6',
        'Mazdaspeed 3',
        'Mazdaspeed6',
        'Miata MX-5',
        'Millenia',
        'MPV',
        'MX-3',
        'MX-5',
        'MX-6',
        'Navajo',
        'Protege',
        'Protege5',
        'RX-7',
        'RX-8',
        'Tribute',
      ],
      'Mercedes-Benz' => [
        '190E',
        '300CE',
        '300D',
        '300E',
        '300SD',
        '300SE',
        '300SL',
        '300TE',
        '400E',
        '400SE',
        '400SEL',
        '500E',
        '500SEC',
        '500SEL',
        '500SL',
        '600SEC',
        '600SEL',
        '600SL',
        'C-Class',
        'CL-Class',
        'CL65 AMG',
        'CLK-Class',
        'CLS-Class',
        'E-Class',
        'G-Class',
        'G55 AMG',
        'GL-Class',
        'GLK-Class',
        'M-Class',
        'R-Class',
        'S-Class',
        'SL-Class',
        'SL65 AMG',
        'SLK-Class',
        'SLK55 AMG',
        'SLR McLaren',
        'SLS AMG',
        'SLS-Class',
        'Sprinter 2500',
        'Sprinter 3500',
        'Sprinter',
        'W123',
        'W126',
        'W201',
      ],

      'Mercury' => [
        'Capri',
        'Cougar',
        'Grand Marquis',
        'Lynx',
        'Marauder',
        'Mariner',
        'Marquis',
        'Milan',
        'Montego',
        'Monterey',
        'Mountaineer',
        'Mystique',
        'Sable',
        'Topaz',
        'Tracer',
        'Villager',
      ],

      'Mini' => [
        'Clubman',
        'Cooper Clubman',
        'Cooper Countryman',
        'Cooper',
        'Countryman',
        'Mini',
      ],

      'Mitsubishi' => [
        '3000GT',
        'Challenger',
        'Chariot',
        'Cordia',
        'Diamante',
        'Eclipse',
        'Endeavor',
        'Excel',
        'Expo LRV',
        'Expo',
        'Galant',
        'GTO',
        'i-MiEV',
        'L300',
        'Lancer Evolution',
        'Lancer',
        'Mighty Max Macro',
        'Mighty Max',
        'Mirage',
        'Montero Sport',
        'Montero',
        'Outlander Sport',
        'Outlander',
        'Pajero',
        'Precis',
        'Raider',
        'RVR',
        'Sigma',
        'Space',
        'Starion',
        'Tredia',
        'Truck',
        'Tundra',
      ],

      'Nissan' => [
        '200SX',
        '240SX',
        '280ZX',
        '300ZX',
        '350Z Roadster',
        '350Z',
        '370Z',
        'Altima',
        'Armada',
        'Cube',
        'Datsun/Nissan Z-car',
        'Frontier',
        'GT-R',
        'JUKE',
        'Leaf',
        'Maxima',
        'Murano',
        'NV1500',
        'NV2500',
        'NV3500',
        'NX',
        'Pathfinder Armada',
        'Pathfinder',
        'Quest',
        'Rogue',
        'Sentra',
        'Stanza',
        'Titan',
        'Versa',
        'Xterra',
      ],

      'Oldsmobile' => [
        '88',
        '98',
        'Achieva',
        'Alero',
        'Aurora',
        'Bravada',
        'Ciera',
        'Custom Cruiser',
        'Cutlass Cruiser',
        'Cutlass Supreme',
        'Cutlass',
        'Intrigue',
        'LSS',
        'Regency',
        'Silhouette',
        'Toronado',
      ],

      'Plymouth' => [
        'Acclaim',
        'Breeze',
        'Colt Vista',
        'Colt',
        'Fury',
        'Grand Voyager',
        'Horizon',
        'Laser',
        'Neon',
        'Prowler',
        'Reliant',
        'Roadrunner',
        'Sundance',
        'Volare',
        'Voyager',
      ],

      'Pontiac' => [
        '1000',
        '6000',
        'Aztek',
        'Bonneville',
        'Chevette',
        'Daewoo Kalos',
        'Fiero',
        'Firebird Formula',
        'Firebird Trans Am',
        'Firebird',
        'Firefly',
        'G3',
        'G5',
        'G6',
        'G8',
        'GeMini',
        'Grand Am',
        'Grand Prix Turbo',
        'Grand Prix',
        'GTO',
        'LeMans',
        'Montana SV6',
        'Montana',
        'Monterey',
        'Parisienne',
        'Safari',
        'Solstice',
        'Sunbird',
        'Sunfire',
        'Tempest',
        'Torrent',
        'Trans Sport',
        'Turbo Firefly',
        'Vibe',
      ],

      'Ram' => [
        '1500',
        '2500',
        '3500',
        'C/V',
        'Dakota',
      ],

      'Saturn' => [
        'Astra',
        'Aura',
        'Ion',
        'L-Series',
        'Outlook',
        'Relay',
        'S-Series',
        'Sky',
        'VUE',
      ],

      'Subaru' => [
        'Alcyone SVX',
        'B9 Tribeca',
        'Baja',
        'Brat',
        'BRZ',
        'Forester',
        'Impreza WRX',
        'Impreza',
        'Justy',
        'Legacy',
        'Leone',
        'Loyale',
        'Outback Sport',
        'Outback',
        'SVX',
        'Tribeca',
        'XT',
      ],

      'Suzuki' => [
        'Aerio',
        'Cultus',
        'Daewoo Lacetti',
        'Daewoo Magnus',
        'Equator',
        'Esteem',
        'Forenza',
        'Grand Vitara',
        'Kizashi',
        'Reno',
        'Samurai',
        'Sidekick',
        'SJ 410',
        'SJ',
        'Swift',
        'SX4',
        'Verona',
        'Vitara',
        'X-90',
        'XL-7',
        'XL7',
      ],

      'Toyota' => [
        '4Runner',
        'Avalon',
        'Camry Hybrid',
        'Camry Solara',
        'Camry',
        'Celica',
        'Corolla',
        'Cressida',
        'Echo',
        'FJ Cruiser',
        'Highlander Hybrid',
        'Highlander',
        'Ipsum',
        'Land Cruiser',
        'Matrix',
        'MR2',
        'Paseo',
        'Previa',
        'Prius c',
        'Prius Plug-in Hybrid',
        'Prius Plug-in',
        'Prius v',
        'Prius',
        'RAV4',
        'Sequoia',
        'Sienna',
        'Solara',
        'Supra',
        'T100 Xtra',
        'T100',
        'Tacoma Xtra',
        'Tacoma',
        'Tercel',
        'Truck Xtracab SR5',
        'Tundra',
        'TundraMax',
        'Venza',
        'Xtra',
        'Yaris',
      ],

      'Volkswagen' => [
        'Beetle',
        'Cabriolet',
        'CC',
        'Corrado',
        'Eos',
        'Eurovan',
        'Fox',
        'GLI',
        'Golf III',
        'Golf',
        'GTI',
        'Jetta III',
        'Jetta',
        'New Beetle',
        'Passat',
        'Phaeton',
        'Quantum',
        'R32',
        'Rabbit',
        'rio',
        'riolet',
        'Routan',
        'Scirocco',
        'Tiguan',
        'Touareg 2',
        'Touareg',
        'Type 2',
        'Vanagon',
      ],

      'Volvo' => [
        '240',
        '740',
        '850',
        '940',
        '960',
        'C30',
        'C70',
        'S40',
        'S60',
        'S70',
        'S80',
        'S90',
        'V40',
        'V50',
        'V70',
        'V90',
        'XC60',
        'XC70',
        'XC90'
        ]
      ];

    $makes = Make::lists('id', 'name');

    foreach ($models as $make => $models) {
      foreach ($models as $model) {
        Model::create([
          'make_id' => $makes[$make],
          'name' => $model,
          ]);
      }
    }
  }
}
